name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

env:
  DOCKER_CONFIG: ${{ runner.temp }}/docker_login

jobs:
  # Step 1: Build and Push Docker Image
  tag_and_push_image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Step 2: Log in to Azure Container Registry (ACR)
      - name: Log in to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Step 3: Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/analytics-service:${{ github.sha }} .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/analytics-service:${{ github.sha }}

      # Step 4: Tag Image with Git Tag
      - name: Tag Image with Git Tag
        run: |
          GIT_TAG=$([ -z '${{ github.ref_name }}' ] && git describe --tags --abbrev=0 || echo '${{ github.ref_name }}')
          docker tag ${{ secrets.ACR_LOGIN_SERVER }}/analytics-service:${{ github.sha }} ${{ secrets.ACR_LOGIN_SERVER }}/analytics-service:${GIT_TAG}
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/analytics-service:${GIT_TAG}

  # Step 2: Update Helm Chart and Deploy
  update-deployment-dev:
    needs: [tag_and_push_image]
    name: Deploy Image (Dev) - Helm Update (apps-manifest)
    runs-on: ubuntu-latest
    steps:
      # Checkout Main Repository
      - name: Checkout selected ref
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Extract the Git Tag
      - name: Pull this build tag
        run: |
          echo "GIT_TAG=$([ -z '${{ env.GITHUB_REF_NAME }}' ] && git describe --tags --abbrev=0 || echo '${{ env.GITHUB_REF_NAME }}' )" >> $GITHUB_ENV

      # Checkout apps-manifest Repository (No Token Required)
      - uses: actions/checkout@v2
        with:
          repository: PandhuWibowo/apps-manifest
          path: apps-manifest
          fetch-depth: 1

      # Update Helm Chart with New Image Tag
      - name: Update Image Version in Helm Chart (values-dev.yaml)
        uses: fjogeleit/yaml-update-action@v0.7.0
        with:
          valueFile: analytics-service/values-dev.yaml
          propertyPath: "image.tag"
          value: ${{ env.GIT_TAG }}
          repository: PandhuWibowo/apps-manifest
          message: "chore(deploy): [Dev] Update analytics-service image version to (${{ env.GIT_TAG }})"
          createPR: false
          branch: main
          targetBranch: main
          workDir: apps-manifest

      # Optional: Trigger Helm Deployment
      - name: Helm Deployment
        run: |
          helm upgrade --install analytics-service ./analytics-service \
            --namespace dev \
            --values analytics-service/values-dev.yaml
