name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  # Step 1: Build and Push Docker Image
  tag_and_push_image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Log in to Azure Container Registry (ACR) and build the Docker image
      - name: Log in to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/hello-service:${{ github.sha }} .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/hello-service:${{ github.sha }}

      - name: Tag Image with Git Tag
        run: |
          GIT_TAG=$([ -z '${{ github.ref_name }}' ] && git describe --tags --abbrev=0 || git tag -l "${{ github.ref_name }}" | head -n 1) echo "GIT_TAG=${GIT_TAG}" >> $GITHUB_ENV
          docker tag ${{ secrets.ACR_LOGIN_SERVER }}/hello-service:${{ github.sha }} ${{ secrets.ACR_LOGIN_SERVER }}/hello-service:${GIT_TAG}
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/hello-service:${GIT_TAG}

  # Step 2: Update Helm Chart and Deploy
  update-deployment-dev:
    needs: [tag_and_push_image]
    name: Deploy Image (Dev) - Helm Update (apps-manifest)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout selected ref
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Pull this build tag
        run: |
          echo "GIT_TAG=$([ -z '${{ github.ref_name }}' ] && git describe --tags --abbrev=0 || git tag -l "${{ github.ref_name }}" | head -n 1)" >> $GITHUB_ENV

      # Checkout apps-manifest Repository
      - uses: actions/checkout@v2
        with:
          repository: PandhuWibowo/apps-manifest
          path: apps-manifest  # This will clone the apps-manifest repo into the apps-manifest folder
          fetch-depth: 1

      # Set up Azure CLI (Alternative Method)
      - name: Set up Azure CLI (Alternative Method)
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      # Log in to Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Get AKS Credentials
      - name: Get AKS Credentials
        run: |
          az aks get-credentials --resource-group operationtools-general --name operationtools-general-aks

      # Update Image Version in Helm Chart (values-dev.yaml)
      - name: Update Image Version in Helm Chart (values-dev.yaml)
        uses: fjogeleit/yaml-update-action@v0.16.0
        with:
          valueFile: ./hello-service/values-dev.yaml
          propertyPath: "image.tag"
          value: ${{ env.GIT_TAG }}
          repository: PandhuWibowo/apps-manifest
          message: "chore(deploy): [Dev] Update analytics-service image version to (${{ env.GIT_TAG }})"
          createPR: false
          branch: main
          targetBranch: main
          workDir: apps-manifest  # Ensures we're working within the apps-manifest repo
          token: ${{ secrets.PAT_TOKEN }}
      # Helm Deployment to AKS
      - name: Helm Deployment
        run: |
          helm upgrade --install hello-service ./apps-manifest/hello-service \
            --namespace analytics \
            --values ./apps-manifest/hello-service/values-dev.yaml  # Correct path to values-dev.yaml

